### ISSUE TITLE
REQ: delays

### ISSUE THREAD

**Issue by xxxserxxx** [MichaelStraube/edges#1]
A delay between the event and the action, with a test to check if the mouse was still in the corner, would make setting up behaviors nicer and avoid accidental triggers. Something like the `enterDelay` function of [lead](https://github.com/MageJohn/lead), or `-cornerDelay` of xautolock.

**Comment by mistraube** [comment]
Added in 31c8b60. You can set a delay in milliseconds with `-d` or `--delay` now. The maximum delay is 1000, i.e. if you specify a value greater than 1000, it will be set to 1000.

**Comment by xxxserxxx** [comment]
According to `edges --version` I have `3.0.2`. According to the `3.0.2` release, this commit is in there -- and I see the changes.  However, I'm not seeing it in the release. I'm missing something -- any idea what?

![edges](https://github.com/MichaelStraube/edges/assets/60757196/17c3ff55-4077-4c99-b9ed-bfbda022abcd)

**Comment by mistraube** [comment]
It's not in 3.0.2. I have not released a new version with the change yet. Maybe you forgot to pull the latest commits?

**Comment by mistraube** [comment]
However, I just made a new release 3.1.0.
